#!/usr/bin/env bash

echo "-> Installing bundler gem"
gem install bundler

echo "-> Installing gem dependencies with bundler"
bundle install

echo "-> Bump package version"
bundle exec thor version:bump auto --default patch

echo "-> Build package"
bundle exec thor gox:build

echo "-> Create GitHub release and upload build artifacts"
bundle exec thor gh:release
